server:
  port: 9100
spring:
  application:
    name: api-gateway
  main:
    allow-circular-references: true
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeaders=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfiguration:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
